SELECT
    I.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(IFNULL(SUM(REVIEW_SCORE), 0) / COUNT(*), 2) AS SCORE
FROM
    REST_INFO AS I
    LEFT JOIN REST_REVIEW AS R
    ON I.REST_ID = R.REST_ID
WHERE
    ADDRESS LIKE '서울%'
GROUP BY
    REST_ID
HAVING
    SCORE > 0
ORDER BY
    SCORE DESC,
    FAVORITES DESC

# SELECT *
# FROM
#     REST_INFO