WITH RECURSIVE GENERATION AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM
        ECOLI_DATA
    WHERE
        PARENT_ID IS NULL
    UNION ALL
    SELECT
        ED.ID,
        ED.PARENT_ID,
        1 + GENERATION.GENERATION AS GENERATION
    FROM
        ECOLI_DATA AS ED INNER JOIN
        GENERATION ON ED.PARENT_ID = GENERATION.ID
)

SELECT
    COUNT(*) AS COUNT,
    GENERATION
FROM
    GENERATION
WHERE
    ID NOT IN (
        SELECT DISTINCT
            PARENT_ID
        FROM
            ECOLI_DATA
        WHERE
            PARENT_ID IS NOT NULL
    )
GROUP BY
    GENERATION
ORDER BY
    GENERATION ASC